// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listReadyAiBatches: () => typedError<AiBatchSummary[], string>(__TAURI_INVOKE("list_ready_ai_batches")),
	getAiBatchPayload: (batchId: string) => typedError<AiBatchPayload, string>(__TAURI_INVOKE("get_ai_batch_payload", { batchId })),
	getTopicIndexEntries: () => typedError<TopicIndexEntry[], string>(__TAURI_INVOKE("get_topic_index_entries")),
	applyBatchDecision: (request: ApplyBatchDecisionRequest) => typedError<ApplyBatchDecisionResult, string>(__TAURI_INVOKE("apply_batch_decision", { request })),
	getDashboardSnapshot: () => typedError<DashboardSnapshot, string>(__TAURI_INVOKE("get_dashboard_snapshot")),
	getClipboardPage: (request: ClipboardPageRequest) => typedError<ClipboardPage, string>(__TAURI_INVOKE("get_clipboard_page", { request })),
	deleteClipboardCapture: (request: DeleteClipboardCaptureRequest) => typedError<DeleteClipboardCaptureResult, string>(__TAURI_INVOKE("delete_clipboard_capture", { request })),
	getAppSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("get_app_settings")),
	saveAppSettings: (settings: AppSettings) => typedError<AppSettings, string>(__TAURI_INVOKE("save_app_settings", { settings })),
	toggleMainWindowVisibility: () => typedError<boolean, string>(__TAURI_INVOKE("toggle_main_window_visibility")),
	toggleClipboardWindowVisibility: () => typedError<boolean, string>(__TAURI_INVOKE("toggle_clipboard_window_visibility")),
	getLogDirectory: () => typedError<string, string>(__TAURI_INVOKE("get_log_directory")),
	openInPreview: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_in_preview", { path })),
	copyCaptureToClipboard: (capture: ClipboardReplayRequest) => typedError<null, string>(__TAURI_INVOKE("copy_capture_to_clipboard", { capture })),
	returnCaptureToPreviousApp: (capture: ClipboardReplayRequest) => typedError<ClipboardReturnResult, string>(__TAURI_INVOKE("return_capture_to_previous_app", { capture })),
	revealInFileManager: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_in_file_manager", { path })),
};

/* Types */
export type AiBatchCapture = {
	id: string,
	contentKind: string,
	capturedAt: string,
	source: string,
	sourceAppName: string | null,
	sourceAppBundleId: string | null,
	preview: string,
	rawText: string,
	rawRich: string | null,
	rawRichFormat: string | null,
	linkUrl: string | null,
};

export type AiBatchPayload = {
	batch: AiBatchSummary,
	captures: AiBatchCapture[],
	availableTopics: TopicIndexEntry[],
};

export type AiBatchRuntimeState = "ready" | "running" | "schema_failed" | "review_pending" | "reviewed" | "persisting" | "persisted" | "failed";

export type AiBatchSummary = {
	id: string,
	runtimeState: AiBatchRuntimeState,
	createdAt: string,
	triggerReason: string,
	captureCount: number,
	firstCapturedAt: string,
	lastCapturedAt: string,
	sourceIds: string[],
};

export type AiDecision = "archive_to_topic" | "send_to_inbox" | "discard";

export type AppSettings = {
	knowledgeRoot: string,
	baseUrl: string,
	apiKey: string,
	model: string,
	clipboardHistoryDays?: number,
	shortcutOverrides?: { [key in string]: AppShortcutOverride },
};

export type AppShortcutOverride = {
	accelerator?: string | null,
};

export type ApplyBatchDecisionRequest = {
	batchId: string,
	review: BatchDecisionReview,
	feedback: ReviewFeedbackRecord,
};

export type ApplyBatchDecisionResult = {
	batchId: string,
	accepted: boolean,
	mocked: boolean,
	runtimeState: AiBatchRuntimeState,
	message: string,
};

export type BatchDecisionCluster = {
	clusterId: string,
	sourceIds: string[],
	decision: AiDecision,
	topicSlugSuggestion: string | null,
	topicNameSuggestion: string | null,
	title: string,
	summary: string,
	keyPoints: string[],
	tags: string[],
	confidence: number,
	reason: string,
	possibleTopics: PossibleTopicSuggestion[],
	missingContext: string[],
};

export type BatchDecisionReview = {
	reviewId: string,
	batchId: string,
	runtimeState: AiBatchRuntimeState,
	createdAt: string,
	modelSchemaVersion: string,
	clusters: BatchDecisionCluster[],
};

export type CapturePreview = {
	id?: string,
	source?: string,
	sourceAppName?: string | null,
	sourceAppBundleId?: string | null,
	sourceAppIconPath?: string | null,
	contentKind?: string,
	preview?: string,
	secondaryPreview?: string | null,
	capturedAt?: string,
	status?: string,
	rawText?: string,
	rawRich?: string | null,
	rawRichFormat?: string | null,
	linkUrl?: string | null,
	assetPath?: string | null,
	thumbnailPath?: string | null,
	imageWidth?: number | null,
	imageHeight?: number | null,
	byteSize?: number | null,
};

export type ClipboardPage = {
	captures: CapturePreview[],
	page: number,
	pageSize: number,
	total: number,
	hasMore: boolean,
	historyDays: number,
	summary: ClipboardPageSummary,
};

export type ClipboardPageRequest = {
	page: number,
	pageSize: number,
	search: string | null,
	filter: string | null,
};

export type ClipboardPageSummary = {
	total: number,
	text: number,
	links: number,
	images: number,
};

export type ClipboardReplayRequest = {
	captureId: string | null,
	contentKind: string,
	rawText: string,
	rawRich: string | null,
	rawRichFormat: string | null,
	linkUrl: string | null,
	assetPath: string | null,
};

export type ClipboardReturnResult = {
	pasted: boolean,
};

export type DashboardSnapshot = {
	appName: string,
	appVersion: string,
	buildChannel: string,
	appEnv: string,
	dataChannel: string,
	os: string,
	defaultKnowledgeRoot: string,
	appDataDir: string,
	appLogDir: string,
	queuePolicy: string,
	captureMode: string,
	recentCaptures: CapturePreview[],
};

export type DeleteClipboardCaptureRequest = {
	id: string,
};

export type DeleteClipboardCaptureResult = {
	id: string,
	removedFromHistory: boolean,
	removedFromStore: boolean,
	deleted: boolean,
};

export type PossibleTopicSuggestion = {
	topicSlug: string,
	topicName: string,
	reason: string | null,
};

export type ReviewAction = "accept_all" | "accept_with_edits" | "reroute_to_inbox" | "reroute_topic" | "discard";

export type ReviewFeedbackRecord = {
	batchId: string,
	reviewId: string,
	action: ReviewAction,
	editedClusterIds: string[],
	note: string | null,
	submittedAt: string,
};

export type TopicIndexEntry = {
	topicSlug: string,
	topicName: string,
	topicSummary: string,
	recentTags: string[],
	lastUpdatedAt: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

