// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getDashboardSnapshot: () => typedError<DashboardSnapshot, string>(__TAURI_INVOKE("get_dashboard_snapshot")),
	getClipboardPage: (request: ClipboardPageRequest) => typedError<ClipboardPage, string>(__TAURI_INVOKE("get_clipboard_page", { request })),
	deleteClipboardCapture: (request: DeleteClipboardCaptureRequest) => typedError<DeleteClipboardCaptureResult, string>(__TAURI_INVOKE("delete_clipboard_capture", { request })),
	getAppSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("get_app_settings")),
	saveAppSettings: (settings: AppSettings) => typedError<AppSettings, string>(__TAURI_INVOKE("save_app_settings", { settings })),
	getLogDirectory: () => typedError<string, string>(__TAURI_INVOKE("get_log_directory")),
	openInPreview: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_in_preview", { path })),
	copyCaptureToClipboard: (capture: ClipboardReplayRequest) => typedError<null, string>(__TAURI_INVOKE("copy_capture_to_clipboard", { capture })),
	revealInFileManager: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_in_file_manager", { path })),
};

/* Types */
export type AppSettings = {
	knowledgeRoot: string,
	baseUrl: string,
	apiKey: string,
	model: string,
	clipboardHistoryDays?: number,
};

export type CapturePreview = {
	id?: string,
	source?: string,
	sourceAppName?: string | null,
	sourceAppBundleId?: string | null,
	sourceAppIconPath?: string | null,
	contentKind?: string,
	preview?: string,
	secondaryPreview?: string | null,
	capturedAt?: string,
	status?: string,
	rawText?: string,
	rawRich?: string | null,
	rawRichFormat?: string | null,
	linkUrl?: string | null,
	assetPath?: string | null,
	thumbnailPath?: string | null,
	imageWidth?: number | null,
	imageHeight?: number | null,
	byteSize?: number | null,
};

export type ClipboardPage = {
	captures: CapturePreview[],
	page: number,
	pageSize: number,
	total: number,
	hasMore: boolean,
	historyDays: number,
	summary: ClipboardPageSummary,
};

export type ClipboardPageRequest = {
	page: number,
	pageSize: number,
	search: string | null,
	filter: string | null,
};

export type ClipboardPageSummary = {
	total: number,
	text: number,
	links: number,
	images: number,
};

export type ClipboardReplayRequest = {
	contentKind: string,
	rawText: string,
	rawRich: string | null,
	rawRichFormat: string | null,
	linkUrl: string | null,
	assetPath: string | null,
};

export type DashboardSnapshot = {
	appName: string,
	appVersion: string,
	buildChannel: string,
	appEnv: string,
	dataChannel: string,
	os: string,
	defaultKnowledgeRoot: string,
	appDataDir: string,
	appLogDir: string,
	queuePolicy: string,
	captureMode: string,
	recentCaptures: CapturePreview[],
};

export type DeleteClipboardCaptureRequest = {
	id: string,
};

export type DeleteClipboardCaptureResult = {
	id: string,
	removedFromHistory: boolean,
	removedFromStore: boolean,
	deleted: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

