// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	listReadyAiBatches: () => typedError<AiBatchSummary[], IpcError>(__TAURI_INVOKE("list_ready_ai_batches")),
	getAiBatchPayload: (batchId: string) => typedError<AiBatchPayload, IpcError>(__TAURI_INVOKE("get_ai_batch_payload", { batchId })),
	getTopicIndexEntries: () => typedError<TopicIndexEntry[], IpcError>(__TAURI_INVOKE("get_topic_index_entries")),
	applyBatchDecision: (request: ApplyBatchDecisionRequest) => typedError<ApplyBatchDecisionResult, IpcError>(__TAURI_INVOKE("apply_batch_decision", { request })),
	getAiSystemSnapshot: () => typedError<AiSystemSnapshot, string>(__TAURI_INVOKE("get_ai_system_snapshot")),
	recordAiFeedbackEvent: (input: RecordFeedbackEventInput) => typedError<RecordFeedbackEventResult, string>(__TAURI_INVOKE("record_ai_feedback_event", { input })),
	previewAiBatchCompile: (batchId: string) => typedError<BatchCompilePreviewResult, string>(__TAURI_INVOKE("preview_ai_batch_compile", { batchId })),
	listHomeChatConversations: () => typedError<HomeChatConversationSummary[], string>(__TAURI_INVOKE("list_home_chat_conversations")),
	getHomeChatConversation: (conversationId: string) => typedError<HomeChatConversationDetail, string>(__TAURI_INVOKE("get_home_chat_conversation", { conversationId })),
	createHomeChatConversation: (request: CreateHomeChatConversationRequest) => typedError<HomeChatConversationDetail, string>(__TAURI_INVOKE("create_home_chat_conversation", { request })),
	appendHomeChatUserMessage: (request: AppendHomeChatUserMessageRequest) => typedError<HomeChatConversationDetail, string>(__TAURI_INVOKE("append_home_chat_user_message", { request })),
	replaceLatestHomeChatAssistantMessage: (request: ReplaceLatestHomeChatAssistantMessageRequest) => typedError<HomeChatConversationDetail, string>(__TAURI_INVOKE("replace_latest_home_chat_assistant_message", { request })),
	rewriteLatestHomeChatUserMessage: (request: RewriteLatestHomeChatUserMessageRequest) => typedError<HomeChatConversationDetail, string>(__TAURI_INVOKE("rewrite_latest_home_chat_user_message", { request })),
	updateHomeChatConversationTitle: (request: UpdateHomeChatConversationTitleRequest) => typedError<HomeChatConversationSummary, string>(__TAURI_INVOKE("update_home_chat_conversation_title", { request })),
	getDashboardSnapshot: () => typedError<DashboardSnapshot, string>(__TAURI_INVOKE("get_dashboard_snapshot")),
	getClipboardPage: (request: ClipboardPageRequest) => typedError<ClipboardPage, string>(__TAURI_INVOKE("get_clipboard_page", { request })),
	getClipboardBoardBootstrap: () => typedError<ClipboardBoardBootstrap, string>(__TAURI_INVOKE("get_clipboard_board_bootstrap")),
	getPinnedClipboardCaptures: () => typedError<PinnedClipboardCapture[], string>(__TAURI_INVOKE("get_pinned_clipboard_captures")),
	setClipboardCapturePinned: (request: SetClipboardCapturePinnedRequest) => typedError<UpdateClipboardPinResult, string>(__TAURI_INVOKE("set_clipboard_capture_pinned", { request })),
	deleteClipboardCapture: (request: DeleteClipboardCaptureRequest) => typedError<DeleteClipboardCaptureResult, string>(__TAURI_INVOKE("delete_clipboard_capture", { request })),
	getAppSettings: () => typedError<AppSettings, string>(__TAURI_INVOKE("get_app_settings")),
	listClipboardSourceApps: () => typedError<ClipboardSourceAppOption[], string>(__TAURI_INVOKE("list_clipboard_source_apps")),
	getClipboardSourceAppIcons: (appPaths: string[]) => typedError<ClipboardSourceAppIconResult[], string>(__TAURI_INVOKE("get_clipboard_source_app_icons", { appPaths })),
	reportAppActivity: () => typedError<null, string>(__TAURI_INVOKE("report_app_activity")),
	saveAppSettings: (settings: AppSettings) => typedError<AppSettings, IpcError>(__TAURI_INVOKE("save_app_settings", { settings })),
	toggleMainWindowVisibility: () => typedError<boolean, string>(__TAURI_INVOKE("toggle_main_window_visibility")),
	toggleClipboardWindowVisibility: () => typedError<boolean, string>(__TAURI_INVOKE("toggle_clipboard_window_visibility")),
	getClipboardWindowTargetAppName: () => typedError<string | null, string>(__TAURI_INVOKE("get_clipboard_window_target_app_name")),
	getLogDirectory: () => typedError<string, string>(__TAURI_INVOKE("get_log_directory")),
	openInPreview: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_in_preview", { path })),
	copyCaptureToClipboard: (capture: ClipboardReplayRequest) => typedError<null, IpcError>(__TAURI_INVOKE("copy_capture_to_clipboard", { capture })),
	returnCaptureToPreviousApp: (capture: ClipboardReplayRequest) => typedError<ClipboardReturnResult, IpcError>(__TAURI_INVOKE("return_capture_to_previous_app", { capture })),
	getAccessibilityPermissionStatus: () => __TAURI_INVOKE<boolean>("get_accessibility_permission_status"),
	openAccessibilitySettings: () => typedError<null, IpcError>(__TAURI_INVOKE("open_accessibility_settings")),
	requestAppRestart: () => typedError<null, string>(__TAURI_INVOKE("request_app_restart")),
	revealInFileManager: (path: string) => typedError<null, string>(__TAURI_INVOKE("reveal_in_file_manager", { path })),
};

/** Events */
export const events = {
	appSettingsChanged: makeEvent<AppSettingsChanged>("app-settings-changed"),
	clipboardCapturesUpdated: makeEvent<ClipboardCapturesUpdated>("clipboard-captures-updated"),
	homeChatConversationsUpdated: makeEvent<HomeChatConversationsUpdated>("home-chat-conversations-updated"),
};

/* Types */
export type AiBatchCapture = {
	id: string,
	contentKind: string,
	capturedAt: string,
	source: string,
	sourceAppName: string | null,
	sourceAppBundleId: string | null,
	preview: string,
	rawText: string,
	rawRich: string | null,
	rawRichFormat: string | null,
	linkUrl: string | null,
};

export type AiBatchPayload = {
	batch: AiBatchSummary,
	captures: AiBatchCapture[],
	availableTopics: TopicIndexEntry[],
};

export type AiBatchRuntimeState = "ready" | "running" | "schema_failed" | "review_pending" | "reviewed" | "persisting" | "persisted" | "failed";

export type AiBatchSummary = {
	id: string,
	runtimeState: AiBatchRuntimeState,
	createdAt: string,
	triggerReason: string,
	captureCount: number,
	firstCapturedAt: string,
	lastCapturedAt: string,
	sourceIds: string[],
};

export type AiCapabilitySnapshot = {
	interactiveConfigured: boolean,
	backgroundCompileConfigured: boolean,
	backgroundSourceKind: BackgroundCompileSourceKind,
	backgroundSourceLabel: string,
	backgroundSourceReason: string | null,
	activeProviderId: string | null,
	activeProviderName: string | null,
	activeVendor: RuntimeProviderVendor | null,
};

export type AiDecision = "archive_to_topic" | "send_to_inbox" | "discard";

export type AiSystemPhase = "contract_reset" | "storage_reset" | "capability_boundary" | "background_compiler" | "quality_loop" | "ai_ops";

export type AiSystemSnapshot = {
	phase: AiSystemPhase,
	capability: AiCapabilitySnapshot,
	runtime: BatchCompilerRuntimeSnapshot,
	feedbackEventCount: number,
	latestQualitySnapshot: QualitySnapshot | null,
	recentJobs: BatchCompileJob[],
	recentWrites: PersistedKnowledgeWrite[],
};

export type AppLocale = "en-US" | "zh-CN";

export type AppLocaleMode = "manual" | "system";

export type AppLocalePreference = {
	mode?: AppLocaleMode,
	locale?: AppLocale | null,
};

export type AppSettings = {
	revision?: number,
	knowledgeRoot: string,
	runtimeProviderProfiles: RuntimeProviderProfile[],
	activeRuntimeProviderId: string,
	localePreference?: AppLocalePreference,
	clipboardHistoryDays?: number,
	clipboardCaptureEnabled?: boolean,
	clipboardExcludedSourceApps?: ClipboardSourceAppRule[],
	clipboardExcludedKeywords?: string[],
	shortcutOverrides?: { [key in string]: AppShortcutOverride },
};

export type AppSettingsChanged = {
	previous: AppSettings | null,
	saved: AppSettings,
	sourceWindowLabel: string | null,
};

export type AppShortcutOverride = {
	accelerator?: string | null,
};

export type AppendHomeChatUserMessageRequest = {
	conversationId: string,
	userMessage: string,
};

export type ApplyBatchDecisionRequest = {
	batchId: string,
	review: BatchDecisionReview,
	feedback: ReviewFeedbackRecord,
};

export type ApplyBatchDecisionResult = {
	batchId: string,
	accepted: boolean,
	mocked: boolean,
	runtimeState: AiBatchRuntimeState,
	message: string,
	persistedOutputs: PersistedKnowledgeOutput[],
};

export type BackgroundCompileSourceKind = "injected_mock" | "provider_profile" | "unavailable";

export type BatchCompileDecision = {
	decisionId: string,
	disposition: BatchCompileDisposition,
	sourceCaptureIds: string[],
	topicSlug: string | null,
	topicName: string | null,
	title: string,
	summary: string,
	keyPoints: string[],
	tags: string[],
	confidence: number,
	rationale: string,
};

export type BatchCompileDisposition = "write_topic" | "write_inbox" | "discard_noise";

export type BatchCompileInput = {
	batchId: string | null,
	trigger: BatchCompileTrigger,
	captureCount: number,
	sourceCaptureIds: string[],
	firstCapturedAt: string | null,
	lastCapturedAt: string | null,
};

export type BatchCompileJob = {
	id: string,
	status: BatchCompileJobStatus,
	queuedAt: string,
	startedAt: string | null,
	finishedAt: string | null,
	attempt: number,
	input: BatchCompileInput,
	decisions: BatchCompileDecision[],
	persistedWrites: PersistedKnowledgeWrite[],
	failureReason: string | null,
};

export type BatchCompileJobStatus = "queued" | "running" | "model_complete" | "write_pending" | "persisted" | "failed" | "abandoned";

export type BatchCompilePreviewResult = {
	batchId: string,
	sourceKind: BackgroundCompileSourceKind,
	sourceLabel: string,
	decisions: BatchCompileDecision[],
};

export type BatchCompileRuntimeStatus = "not_bootstrapped" | "awaiting_capability" | "idle" | "running" | "retry_backoff" | "blocked";

export type BatchCompileTrigger = "capture_count" | "max_wait" | "manual_replay" | "manual_retry";

export type BatchCompilerRuntimeSnapshot = {
	status: BatchCompileRuntimeStatus,
	observedPendingCaptureCount: number,
	observedBatchBacklogCount: number,
	activeJob: BatchCompileJob | null,
	lastTransitionAt: string | null,
	lastError: string | null,
};

export type BatchDecisionCluster = {
	clusterId: string,
	sourceIds: string[],
	decision: AiDecision,
	topicSlugSuggestion: string | null,
	topicNameSuggestion: string | null,
	title: string,
	summary: string,
	keyPoints: string[],
	tags: string[],
	confidence: number,
	reason: string,
	possibleTopics: PossibleTopicSuggestion[],
	missingContext: string[],
};

export type BatchDecisionReview = {
	reviewId: string,
	batchId: string,
	runtimeState: AiBatchRuntimeState,
	createdAt: string,
	modelSchemaVersion: string,
	clusters: BatchDecisionCluster[],
};

export type CapturePreview = {
	id?: string,
	source?: string,
	sourceAppName?: string | null,
	sourceAppBundleId?: string | null,
	sourceAppIconPath?: string | null,
	contentKind?: string,
	preview?: string,
	secondaryPreview?: string | null,
	capturedAt?: string,
	status?: string,
	rawText?: string,
	ocrText?: string | null,
	fileMissing?: boolean,
	rawRich?: string | null,
	rawRichFormat?: string | null,
	linkUrl?: string | null,
	linkMetadata?: LinkMetadata | null,
	assetPath?: string | null,
	thumbnailPath?: string | null,
	imageWidth?: number | null,
	imageHeight?: number | null,
	byteSize?: number | null,
};

export type ClipboardBoardBootstrap = {
	page: ClipboardPage,
	pinnedCaptures: PinnedClipboardCapture[],
};

export type ClipboardCapturesUpdated = {
	reason: ClipboardCapturesUpdatedReason,
	refreshHistory: boolean,
	refreshPinned: boolean,
	refreshDashboard: boolean,
};

export type ClipboardCapturesUpdatedReason = "historyChanged" | "pinsChanged" | "captureDeleted" | "ocrUpdated" | "linkMetadataUpdated" | "runtimeStateChanged";

export type ClipboardPage = {
	captures: CapturePreview[],
	page: number,
	pageSize: number,
	total: number,
	hasMore: boolean,
	historyDays: number,
	summary: ClipboardPageSummary,
};

export type ClipboardPageRequest = {
	page: number,
	pageSize: number,
	search: string | null,
	filter: string | null,
};

export type ClipboardPageSummary = {
	total: number,
	text: number,
	links: number,
	images: number,
	videos: number,
	files: number,
};

export type ClipboardReplayRequest = {
	captureId: string | null,
	contentKind: string,
	rawText: string,
	rawRich: string | null,
	rawRichFormat: string | null,
	linkUrl: string | null,
	assetPath: string | null,
};

export type ClipboardReturnResult = {
	pasted: boolean,
};

export type ClipboardSourceAppIconResult = {
	appPath: string,
	iconPath: string | null,
};

export type ClipboardSourceAppOption = {
	bundleId: string,
	appName: string,
	appPath: string | null,
	iconPath: string | null,
};

export type ClipboardSourceAppRule = {
	bundleId: string,
	appName: string,
};

export type CreateHomeChatConversationRequest = {
	initialUserMessage: string,
};

export type DashboardSnapshot = {
	appName: string,
	appVersion: string,
	buildChannel: string,
	appEnv: string,
	dataChannel: string,
	os: string,
	defaultKnowledgeRoot: string,
	appDataDir: string,
	appLogDir: string,
	queuePolicy: string,
	captureMode: string,
	recentCaptures: CapturePreview[],
};

export type DeleteClipboardCaptureRequest = {
	id: string,
};

export type DeleteClipboardCaptureResult = {
	id: string,
	removedFromHistory: boolean,
	removedFromStore: boolean,
	removedFromPinned: boolean,
	deleted: boolean,
};

export type FeedbackEvent = {
	id: string,
	kind: FeedbackEventKind,
	source: FeedbackEventSource,
	jobId: string | null,
	writeId: string | null,
	sourceCaptureIds: string[],
	topicSlug: string | null,
	targetTopicSlug: string | null,
	recordedAt: string,
	note: string | null,
};

export type FeedbackEventKind = "topic_confirmed" | "topic_reassigned" | "routed_to_inbox" | "restored_to_topic" | "discarded_as_noise" | "knowledge_retained" | "knowledge_deleted" | "topic_viewed";

export type FeedbackEventSource = "user" | "system" | "migration";

export type HomeChatConversationDetail = {
	conversation: HomeChatConversationSummary,
	messages: HomeChatMessage[],
};

export type HomeChatConversationSummary = {
	id: string,
	title: string | null,
	titleStatus: HomeChatConversationTitleStatus,
	titleSource: HomeChatConversationTitleSource | null,
	previewText: string | null,
	messageCount: number,
	createdAt: string,
	updatedAt: string,
	lastMessageAt: string,
};

export type HomeChatConversationTitleSource = "model" | "fallback" | "manual";

export type HomeChatConversationTitleStatus = "pending" | "ready" | "failed" | "fallback";

export type HomeChatConversationsUpdated = {
	reason: HomeChatConversationsUpdatedReason,
	conversationId: string | null,
	refreshList: boolean,
	refreshConversation: boolean,
};

export type HomeChatConversationsUpdatedReason = "conversationCreated" | "messagesChanged" | "titleChanged";

export type HomeChatMessage = {
	id: string,
	conversationId: string,
	ordinal: number,
	role: HomeChatMessageRole,
	content: string,
	reasoningText: string | null,
	status: HomeChatMessageStatus,
	errorMessage: string | null,
	providerLabel: string | null,
	responseModel: string | null,
	createdAt: string,
	updatedAt: string,
};

export type HomeChatMessageRole = "user" | "assistant";

export type HomeChatMessageStatus = "completed" | "failed" | "stopped";

export type IpcError = {
	code: IpcErrorCode,
	message: string,
	details: string | null,
};

export type IpcErrorCode = "validation_error" | "state_conflict" | "not_found" | "permission_required" | "packaged_app_required" | "local_signing_required" | "signature_invalid" | "io_error" | "platform_error" | "internal_error";

export type KnowledgeWriteDestination = "topic" | "inbox";

export type LinkMetadata = {
	title?: string | null,
	description?: string | null,
	iconPath?: string | null,
	fetchedAt?: string,
	fetchStatus?: LinkMetadataFetchStatus,
};

export type LinkMetadataFetchStatus = "pending" | "ready" | "skipped" | "failed";

export type PersistedKnowledgeDestination = "topic" | "inbox" | "discard";

export type PersistedKnowledgeOutput = {
	clusterId: string,
	destination: PersistedKnowledgeDestination,
	filePath: string | null,
	topicSlug: string | null,
	topicName: string | null,
};

export type PersistedKnowledgeWrite = {
	writeId: string,
	jobId: string,
	decisionId: string,
	destination: KnowledgeWriteDestination,
	knowledgePath: string,
	topicSlug: string | null,
	topicName: string | null,
	title: string,
	sourceCaptureIds: string[],
	persistedAt: string,
};

export type PinnedClipboardCapture = {
	capture?: CapturePreview,
	pinnedAt?: string,
};

export type PossibleTopicSuggestion = {
	topicSlug: string,
	topicName: string,
	reason: string | null,
};

export type QualitySnapshot = {
	id: string,
	generatedAt: string,
	totalFeedbackEvents: number,
	classificationFeedbackCount: number,
	correctionEventCount: number,
	correctionRate: number | null,
	topicConfirmedCount: number,
	topicReassignedCount: number,
	inboxRerouteCount: number,
	restoredToTopicCount: number,
	discardedCount: number,
	retainedCount: number,
	deletedCount: number,
	viewedCount: number,
	lastFeedbackAt: string | null,
};

export type RecordFeedbackEventInput = {
	kind: FeedbackEventKind,
	source: FeedbackEventSource,
	jobId: string | null,
	writeId: string | null,
	sourceCaptureIds: string[],
	topicSlug: string | null,
	targetTopicSlug: string | null,
	note: string | null,
};

export type RecordFeedbackEventResult = {
	event: FeedbackEvent,
	qualitySnapshot: QualitySnapshot,
};

export type ReplaceLatestHomeChatAssistantMessageRequest = {
	conversationId: string,
	content: string,
	reasoningText: string | null,
	status: HomeChatMessageStatus,
	errorMessage: string | null,
	providerLabel: string | null,
	responseModel: string | null,
};

export type ReviewAction = "accept_all" | "accept_with_edits" | "reroute_to_inbox" | "reroute_topic" | "discard";

export type ReviewFeedbackRecord = {
	batchId: string,
	reviewId: string,
	action: ReviewAction,
	editedClusterIds: string[],
	note: string | null,
	submittedAt: string,
};

export type RewriteLatestHomeChatUserMessageRequest = {
	conversationId: string,
	userMessage: string,
};

export type RuntimeProviderProfile = {
	id: string,
	name: string,
	vendor: RuntimeProviderVendor,
	baseUrl: string,
	apiKey: string,
	model?: string,
};

export type RuntimeProviderVendor = "openai" | "deepseek";

export type SetClipboardCapturePinnedRequest = {
	capture: CapturePreview,
	pinned: boolean,
	replaceOldest?: boolean,
};

export type TopicIndexEntry = {
	topicSlug: string,
	topicName: string,
	topicSummary: string,
	recentTags: string[],
	lastUpdatedAt: string,
};

export type UpdateClipboardPinResult = {
	captureId: string,
	pinned: boolean,
	changed: boolean,
	replacedCaptureId: string | null,
	pinnedCount: number,
};

export type UpdateHomeChatConversationTitleRequest = {
	conversationId: string,
	title: string,
	titleStatus: HomeChatConversationTitleStatus,
	titleSource: HomeChatConversationTitleSource,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

